embabel:
  models:
    default-llm: qwen/qwen3-4b-2507
    default-embedding-model: text-embedding-nomic-embed-text-v1.5
    llms:
      best: qwen/qwen3-4b-2507
      cheapest: qwen/qwen3-4b-2507
    embedding-services:
      best: text-embedding-nomic-embed-text-v1.5
      cheapest: text-embedding-nomic-embed-text-v1.5
  agent-platform:
    ranking:
      llm: qwen/qwen3-4b-2507
  agent:
    platform:
      models:
        lmstudio:
          base-url: http://localhost:1234 # Default
